/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/expenseRegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/expenseStats`; params?: Router.UnknownInputParams; } | { pathname: `/incomeStats`; params?: Router.UnknownInputParams; } | { pathname: `/totalList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tabLayout` | `/tabLayout`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/expenseRegisterScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/expenseStats`; params?: Router.UnknownOutputParams; } | { pathname: `/incomeStats`; params?: Router.UnknownOutputParams; } | { pathname: `/totalList`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tabLayout` | `/tabLayout`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/expenseRegisterScreen${`?${string}` | `#${string}` | ''}` | `/expenseStats${`?${string}` | `#${string}` | ''}` | `/incomeStats${`?${string}` | `#${string}` | ''}` | `/totalList${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tabLayout${`?${string}` | `#${string}` | ''}` | `/tabLayout${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/expenseRegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/expenseStats`; params?: Router.UnknownInputParams; } | { pathname: `/incomeStats`; params?: Router.UnknownInputParams; } | { pathname: `/totalList`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tabLayout` | `/tabLayout`; params?: Router.UnknownInputParams; };
    }
  }
}
